[package]
name = "annil_serverless"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.8", features = ["web-axum"] }
axum = { version = "0.5.17", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
sync_wrapper = "0.1.1"
# anni-provider = "0.1"
# anni-provider = { git = "https://github.com/snylonue/anni.git", package = "anni-provider", branch = "serverless", version = "0.1.1"}
anni-provider-drive-token-storage = { version = "0.1.1" }
uuid = { version = "1", features = ["serde"]}
tokio-util = { version = "0.6.10", features = ["compat", "io"] }
tower-http = { version = "0.3", features = ["cors"]}
shuttle-persist = "0.8"
shuttle-secrets = "0.8"
anyhow = "1.0.66"
serde_json = "1.0.89"

[patch.crates-io]
rusqlite = { git = "https://github.com/ProjectAnni/rusqlite", branch = "wasm32-unknown-unknown" }
# shuttle-service = { git = "https://github.com/snylonue/shuttle.git", branch = "tokio-dep" }