[package]
name = "annil_serverless"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.7.2", features = ["web-axum"] }
axum = { version = "0.5.17", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
sync_wrapper = "0.1.1"
# anni-provider = { git = "https://github.com/ProjectAnni/anni.git", package = "anni-provider" }
anni-provider = { path = "../anni/anni-provider" }

[patch.crates-io]
rusqlite = { git = "https://github.com/ProjectAnni/rusqlite", branch = "wasm32-unknown-unknown" }
shuttle-service = { git = "https://github.com/snylonue/shuttle.git", branch = "tokio-dep" }