name: Shuttle deploy

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Add secrets
        run: |
          # Generate Secrets file
          echo `onedrive_key = ${{ secrets.onedrive_key }}` >> Secrets.toml
          echo `sign_key = ${{ secrets.sign_key }}` >> Secrets.toml
          echo `share_key = ${{ secrets.share_key }}` >> Secrets.toml
          echo `share_key_id = ${{ secrets.share_key_id }}` >> Secrets.toml
          echo `admin_token = ${{ secrets.admin_token }}` >> Secrets.toml
      - uses: shuttle-hq/deploy-action@v0.0.3
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          allow-dirty: true
